### ISSUE TITLE
Example fails to redner

### ISSUE THREAD

**Issue by eugenesvk** [plotly/plotly-notebook-js#1]
I tried opening with `jupyter notebook` from within the `...\Node.js\bin\node_modules\plotly-notebook-js` and running the default plot from your description page
```
var Plot = require('plotly-notebook-js');
var myPlot = Plot.createPlot([{ x: [1,2,3], y: [3,4,5] }], { title: 'Plotly in Jupyter!' });
$$html$$ = myPlot.render();
```
but I get nothing — just empty `OUT[1]` when I hit "Shift+Enter" on this code. A python notebook example works fine as well as example commands from https://github.com/n-riesco/ijavascript.
Since it doesn't display any errors, not really sure how to troubleshoot it.
Any ideas on how to make it work?

Windows 10
Node.js 5.9.1
Jupyter installed via Miniconda3 in root environment
Chrome 49.0.2623.87 m (64-bit), but also tried in Edge as well as with addons disabled

**Comment by mdtusz** [comment]
I'll take a look into this. The ijavascript project has changed fairly rapidly, so it's possible that there are some incompatibilities since this was first published.

**Comment by eugenesvk** [comment]
Ok, thank you.

**Comment by mdtusz** [comment]
After re-reading your issue, I thing I see why it's not working. You need to start the notebook from a path where it can access `node_modules`.

Ideally, you should install `plotly-notebook-js` as a module in the directory where you wish to save the notebook e.g. `~/MyDocuments/my_notebooks/` (I know that's not how windows paths look, but you get the idea).

Your project directory should then be something like this:

```
├── someNotebookName.ipynb
├── maybeSomeOtherNotebook.ipynb
└── node_modules
    └── plotly-notebook-js
```

I haven't tested using `npm install -g` with the notebook and it *shouldn't* be installed globally as it's not an executable.

**Comment by eugenesvk** [comment]
Wow, thanks, that turns out to be simple enough! It also works when I launch `jupyter notebook` from `Node.js\bin`, where global `node_modules` folder is located. You're right, it just needs to be launched from any path that has `node_modules\plotly-notebook-js` in it

Any idea on how to make it able to read global modules? I just don't really understand why I need to install `plotly-notebook-js` in each location I have a notebook in instead of being able to just install it once globally and be able to use it from wherever. Like I can use global gems in Ruby without having to duplicate them in each of the apps depending on a given gem. I now realize that npm convention is different and global means something else, but maybe you have an idea how to make it a bit more convenient.

**Comment by mdtusz** [comment]
Using global packages *could* be done, but as far as I know, it's something that would need to be implemented by the maintainer of IJavascript.

**Comment by eugenesvk** [comment]
By the way, do you know how to save the resulting chart to a local svg file from within the notebook?
